"""Data models and schemas."""

from .test_case import (
    CommitTestCaseRequest,
    CommitTestCaseResponse,
    Priority,
    APITestRequest,
    UITestRequest,
    GenerateAutoTestCaseRequest,
    GenerateAutoTestCaseResponse,
    TestCase,
    TestCaseStep,
    GenerateManualTestCaseRequest,
    GenerateManualTestCaseResponse,
    GenerateBatchTestCaseRequest,
    CoverageAnalysis,
    CoverageGap,
    DuplicateTest,
    GapSeverity,
    IssueSeverity,
    OptimizationSuggestion,
    OptimizeTestCaseResponse,
    OptimizeTestCaseRequest,
    ValidationResult,
    ValidationIssue,
    ValidateTestCaseResponse,
    ValidateTestCaseRequest,
)
from .test_plan import GenerateTestPlanRequest, GenerateTestPlanResponse
from .defect_analysis import (
    AnalyzeDefectRequest,
    AnalyzeDefectResponse,
    DefectHotspot,
    DefectRecord,
)

__all__ = [
    "Priority",
    "TestCase",
    "TestCaseStep",
    "GenerateManualTestCaseRequest",
    "GenerateManualTestCaseResponse",
    "GenerateBatchTestCaseRequest",
    "CoverageAnalysis",
    "DuplicateTest",
    "CoverageGap",
    "GapSeverity",
    "IssueSeverity",
    "OptimizationSuggestion",
    "OptimizeTestCaseResponse",
    "OptimizeTestCaseRequest",
    "ValidationResult",
    "ValidationIssue",
    "ValidateTestCaseResponse",
    "ValidateTestCaseRequest",
    "GenerateAutoTestCaseRequest",
    "GenerateAutoTestCaseResponse",
    "UITestRequest",
    "APITestRequest",
    "CommitTestCaseRequest",
    "CommitTestCaseResponse",
    "GenerateTestPlanRequest",
    "GenerateTestPlanResponse",
    "AnalyzeDefectRequest",
    "AnalyzeDefectResponse",
    "DefectHotspot",
    "DefectRecord",
]
